[package]
name = 'bash-args'
slug = 'bash_args'
version = '0.9.2'
authors = ['Edwin Kofler" <edwin@kofler.dev>']
description = 'A cute little Bash library for blazing fast argument parsing'

[run]
dependencies = ['https://github.com/hyperupcall/bash-core.git@v0.2.0']
sourceDirs = ['pkg/src', 'pkg/src/public']
builtinDirs = []
binDirs = []
completionDirs = []
manDirs = []

[run.shellEnvironment]

[run.setOptions]
errexit = 'on'
pipefail = 'on'

[run.shoptOptions]
shift_verbose = 'on'
