[package]
type = 'bash'
name = 'bash-args'
slug = 'bash_args'
version = '0.10.0'
authors = ['Edwin Kofler <edwin@kofler.dev>']
description = 'A cute little Bash library for blazing fast argument parsing'

[run]
dependencies = ['https://github.com/hyperupcall/bash-core@v0.3.2']
sourceDirs = ['pkg/src/public', 'pkg/src/util']
builtinDirs = []
binDirs = []
completionDirs = []
manDirs = []

[run.shellEnvironment]

[run.setOptions]
errexit = 'on'
pipefail = 'on'

[run.shoptOptions]
shift_verbose = 'on'
