image: archlinux
default: main
tasks:
  init:
    command: |
      set -Eeuo pipefail
      pacman -Syu --noconfirm base-devel sudo man-db expect

      groupadd sudo
      sed -ie 's/# %sudo/%sudo/g' /etc/sudoers

      useradd -m op -s /bin/bash -G sudo
      chpasswd <<< 'op:password'

  main:
    dependencies: [ init ]
    cache: false
    user: op
    mount_paths:
      - .
    command: |
      set -Eeuo pipefail
      sudo -S -v <<< $'password\n'
      source makepkg -Ccfi --noconfirm
